#!/bin/sh
cd /
IFACE=eth0
read MAC </sys/class/net/$IFACE/address
echo $IFACE $MAC

MAC="a1geo"
grep -w -i "$MAC" configFile.txt|while read x
do
set $x
echo $1 $2 $3 $4
done

sudo hostname newhost box
#hsetroot -full /opt/backgrounds/wall.jpg




#==============================

sudo tar -xvf /tce.tar
#sudo tar -zxvf /mydata.tgz


for file in /tce/optional/*.tcz;do
tce-load -i $file
done

sudo rm /tce.tar
sudo rm -rf /tce
sudo mv /rdp /home/tc/rdp
exit
#startx
aterm -e sh -c 'sudo mv /wall.jpg /opt/backgrounds/wall.jpg;hsetroot -full /opt/backgrounds/wall.jpg'


#startx

#aterm -e sh -c 'sudo hsetroot -full /opt/backgrounds/wall.jpg'
#sh /rdp.txt

#sudo mkdir /tce

#tce-load -wi  Xprogs  rdesktop 
#echo GIVE the IP
#read IP
#rdesktop -f $IP


